In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller

## 1. Import given data “milk.csv”

In [17]:
ds = pd.read_csv('data/milk.csv')

ds.shape

(169, 2)

## 2. display first 5 rows and last five rows of the data

In [18]:
ds.head()

     Month  Monthly milk production: pounds per cow. Jan 62 ? Dec 75
0  1962-01                                              589.0
1  1962-02                                              561.0
2  1962-03                                              640.0
3  1962-04                                              656.0
4  1962-05                                              727.0

In [19]:
ds.tail()

,Month,Monthly milk production: pounds per cow. Jan 62 ? Dec 75
164,1975-09,817.0
165,1975-10,827.0
166,1975-11,797.0
167,1975-12,843.0
168,Monthly milk production: pounds per cow. Jan 6...,NaN

## 3. Convert the data type of month column from object data type to datetime format.

In [20]:
ds = ds.drop(ds.index[-1])
ds.columns = ['Month', 'Monthly Milk Production (pounds per cow)']

ds.tail(3)

       Month  Monthly Milk Production (pounds per cow)
165  1975-10                                     827.0
166  1975-11                                     797.0
167  1975-12                                     843.0

In [25]:
ds['Month'] = pd.to_datetime(ds['Month'], format='%Y-%m')

ds['Month'].head()

0   1962-01-01
1   1962-02-01
2   1962-03-01
3   1962-04-01
4   1962-05-01
Name: Month, dtype: datetime64[us]

## 4. set month column as the index of the dataframe.

## 5. Show the line-plot of the given time series data